### ISSUE TITLE
Communication errors in web-interface

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#77]
Sometimes web-interface looses connection to NZBGet, even on local network without network issues.

**Comment by hugbug** [comment]
**Comments from commit https://github.com/nzbget/nzbget/commit/12b6a2602a6dd553bc39d8b596716d2896801c63:**

---

@modest commented on 12b6a26 12 hours ago
This totally fixes the issues with nzbget and Safari. Thanks!

---

@hugbug commented on 12b6a26 11 hours ago
That's very good to know. Can you please post more details about your system - was nzbget running on Mac or on another device (when you had communication errors)?

I have sent this patch before to a user having errors when connecting from Safari/Mac to nzbget running on NAS, but the patch unfortunately didn't fix the problem for him. It however did help another user having issues with Firefox on Windows, that's why I've committed the patch with a hope it helps someone else too.

---

@modest commented on 12b6a26 10 hours ago
Safari issues were with:
- nzbget 16.0-testing-r1420
- Ubuntu 14.04 LTS on amd64
- no SSL enabled at the moment, just accessing via HTTP over LAN (to a LAN hostname, "http://myservername.local:6789/")
- Client is Safari 9.0 running on the latest OS X 10.11 beta 8 15A279b
  - Initial page load always worked correctly. But after a few API requests or refreshes, all connections would start failing. (I'm guessing that the first ~8 connections worked fine – the browser's connections-per-host limit – and that things started failing when it started trying to reuse the zombie sockets that were left open.)  The problem could always be resolved by refreshing the page.
- No issues with Chrome at all.

If you need more data for a repro, I can try rolling back.  I had compared the network traffic in the Safari and Chrome web inspectors, and nothing seemed particularly different about Safari's failed requests, which seemed to indicate that the issue was TCP or lower.  No HTTP responses to those failed requests at all.  (And the web inspector isn't super verbose about failed connections... just appears in red.)

---

@hugbug commented on 12b6a26 10 hours ago
Thank you very much for the details.
I'll reach the other user and ask him to make another test with the current version. Hopefully it will for him too this time.

---

@modest commented on 12b6a26 5 hours ago
Ok, unfortunately the issue has returned and still occurs in the latest develop branch :(

Here's what I'm seeing in Wireshark:
- Seemingly randomly, Safari sometimes omits Authentication headers on requests to /jsonrpc
- This happens with simple status update requests.  I've never seen it happen for other requests.  But status updates are also the most common. `{["nocache": 12345, "method": "status", "params": []}`
- When this occurs, the nzbget UI gives up and stops refreshing.

It seems like there's definitely some kind of browser bug here, but I'm not clear on the root cause.

I think including some kind of auth token in cookies or query string might be a good idea for more resilient requests. Other apps tend to use HTTP basic auth as a first step only, translating that into some kind of reusable token.

(Supporting HTTP/1.1 pipelining might be a good idea, too.)

**Comment by hugbug** [comment]
> Other apps tend to use HTTP basic auth as a first step only, translating that into some kind of reusable token.

I don't think the HTTP basic auth can be controlled by the apps. The browser manages it transparently for the apps. They don't even know that the browser adds extra headers and the apps can't remove it as well (I may be wrong).

Nonetheless I can do the auth token thing. But before that please make a test:
- add you Mac IP to option **AuthorizedIP** in NZBGet.

After that NZBGet will not send authorization request and will not check the HTTP auth. If the issue continues after that the extra auth token will not help.

---

When you did Wireshark and saw the request without HTTP auth, did you see the response from NZBGet (401 Unauthorized)?

**Comment by hugbug** [comment]
Update: implemented authorization token.
I have a report from other user about successful fix.

@modest: please test too and report back. Thanks.

**Comment by hugbug** [comment]
As [reported on forum](http://forum.nzbget.net/viewtopic.php?f=3&t=2167) there are issues with reverse proxies apache and nginx.
They are caused by using of custom header **X-Auth-Token** (related to #77), which these proxies use for their own needs. The problem doesn't always appear but depend on authentication mode configured in proxies.

**TODO:** to solve the issue we should rename **X-Auth-Token** to something unique like X-Auth-Token-2 :)

**Comment by parnic** [comment]
Commit e7562b6 still didn't fix things for me. I use nginx as a reverse proxy for all services on my network, so it enforces http basic auth on the frontend, then once I'm through that I can access all services without needing additional auth. NZBGet's removal of the Authorization header kills my ability to access NZBGet and I end up in an infinite password loop.

Commenting out the `xhr.setRequestHeader('Authorization', '');` line from util.js allows everything to work again. I'm using Chrome 45 as my browser.

**Comment by hugbug** [comment]
Got it, thank you.
